<a href="https://colab.research.google.com/github/Carol-ACDR/Metodos-Numericos/blob/main/ExerciciosEqua%C3%A7%C3%B5esLineares.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DA PARAÍBA – IFPB CAMPUS CAMPINA GRANDE

ENGENHARIA DE COMPUTAÇÃO

DISCIPLINA: Métodos Númericos

PROFESSOR: PAULO RIBEIRO LINS JUNIOR

ALUNO(A): Ana Carolina Dutra Ramos

In [ ]:
import numpy as np
import scipy.linalg as sla

Exercicio 1.1


In [ ]:
#Primeiro
PriA = np.array([[1,2,3],[4,5,6],[7,8,9]])
Prib = np.array([1,1,1])
print(np.linalg.matrix_rank(PriA))
print(np.linalg.matrix_rank(np.c_[PriA, Prib]))
print(PriA.shape[1])

#Segundo

SegA = np.array([[2,3],[-4,-6]])
Segb = np.array([10,-10])
print(np.linalg.matrix_rank(SegA))
print(np.linalg.matrix_rank(np.c_[SegA, Segb]))
print(SegA.shape[1])

2
2
3
1
2
2


Conclusão

a) Sistema possível Indeterminado (infinitas soluções)


b) Sistema impossível (Sem solução precisa)

Exercicio 1.2

In [ ]:
A = np.array([[3,4,-5,1],[0,1,1,-2],[0,0,4,-5],[0,0,0,2]])
b = np.array([-10,-1,3,2])
x4 = 2/2
x3 = (3+5*x4)/4
x2 = -1-x3+2*x4
x1 = (-10-4*x2+5*x3-x4)/3
xteste = [x1,x2,x3,x4]


[1.0, -1.0, 2.0, 1.0]

In [ ]:
def sist_lin_tri_sup(A,b):
 n = len(b)
 x = np.empty(n)
 x[-1] = b[-1]/A[-1, -1]
 for i in range(n-2, -1, -1):
  x[i] = (b[i] - np.sum(A[i,i+1:]*x[i+1:]))/A[i,i]
 return x


In [ ]:
print(xteste)
print(sist_lin_tri_sup(A,b))
print(xteste == sist_lin_tri_sup(A,b))

[1.0, -1.0, 2.0, 1.0]
[ 1. -1.  2.  1.]
[ True  True  True  True]


Exercicio 1.3


In [ ]:
A = np.array([[3,0,0,0],[2,1,0,0],[1,0,1,0],[1,1,1,1]])
b = np.array([4,2,4,2])
x1 = 4/3
x2 = 2 - 2*x1
x3 = 4 -x1
x4 = 2-x1-x2-x3
xteste = [x1,x2,x3,x4]


In [ ]:
def sist_lin_tri_inf(A,b):
 n = len(b)
 x = np.empty(n)
 x[0] = b[0]/A[0, 0]
 for i in range(1,n):
  x[i] = (b[i] - np.sum(A[i,:i]*x[:i]))/A[i,i]
 return x

In [ ]:
print(xteste)
print(sist_lin_tri_inf(A,b))

[1.3333333333333333, -0.6666666666666665, 2.666666666666667, -1.3333333333333337]
[ 1.33333333 -0.66666667  2.66666667 -1.33333333]


Exercicio 1.4

In [ ]:
def triangular(A,b):
  cont = 0
  n = len(b)
  for i in range (0, n):
    for j in range (0,n):
      if (i == j):
        continue
      else:
        cont +=A [i,j]
  if(cont == 0):
    print("Matrix diagonal!")
    return b/A.diagonal()
  else:
    if (A[0,-1] == 0):
      print("Matriz Inferior!")
      x = np.empty(n)
      x[0] = b[0]/A[0, 0]
      for i in range(1,n):
        x[i] = (b[i] - np.sum(A[i,:i]*x[:i]))/A[i,i]
      return x
    else:
      print("Matriz superior!")
      x = np.empty(n)
      x[-1] = b[-1]/A[-1, -1]
      for i in range(n-2, -1, -1):
        x[i] = (b[i] - np.sum(A[i,i+1:]*x[i+1:]))/A[i,i]
      return x


In [ ]:
#teste

InfA = np.array([[3,0,0,0],[2,1,0,0],[1,0,1,0],[1,1,1,1]])
Infb = np.array([4,2,4,2])


SupA = np.array([[3,4,-5,1],[0,1,1,-2],[0,0,4,-5],[0,0,0,2]])
Supb = np.array([-10,-1,3,2])

DigA = np.diag([1,4,2])
Digb = np.array([4, 2, 2])

triangular(InfA,Infb)
triangular(SupA,Supb)
triangular(DigA,Digb)


Matriz Inferior!
Matriz superior!
Matrix diagonal!


array([4. , 0.5, 1. ])