<a href="https://colab.research.google.com/github/Carol-ACDR/Metodos-Numericos/blob/main/ExercicioEliminGaussiana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA DA PARAÍBA – IFPB CAMPUS CAMPINA GRANDE

ENGENHARIA DE COMPUTAÇÃO

DISCIPLINA: Métodos Númericos

PROFESSOR: PAULO RIBEIRO LINS JUNIOR

ALUNO(A): Ana Carolina Dutra Ramos

Função:

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as sla

In [ ]:
def sist_lin_tri_sup(A,b):
 n = len(b)
 x = np.empty(n)
 x[-1] = b[-1]/A[-1, -1]
 for i in range(n-2, -1, -1):
  x[i] = (b[i] - np.sum(A[i,i+1:]*x[i+1:]))/A[i,i]
 return x

def eliminaçãoG(A,b):
  Ab =  np.c_[A,b]
  n = len(A)
  for c in range(n-1):
    aux = np.abs(Ab[c:,c]).argmax()+c
    if (Ab[c,c] == Ab[aux,c]) :
      for d in range(c+1,n):
        Ab[d] = Ab[d] - (((Ab[d,c]/ Ab[c,c]))*Ab[c])
    else:
      Ab[[c,aux]] = Ab [[aux,c]]
      for d in range(c+1,n):
        Ab[d] = Ab[d] - (((Ab[d,c]/ Ab[c,c]))*Ab[c])
  return Ab[:,:-1], Ab[:,-1]

def solução(A,b):
  H,e = eliminaçãoG(A,b)
  return sist_lin_tri_sup(H,e)

a)

In [ ]:
A = np.array([[1.0,1.0,1.0],[4.0,4.0,2.0],[2.0,1.0,-1.0]])
b = np.array([1.0,2.0,0.0])
print(solução(A,b))
print(sla.solve(A, b, lower=False))
print(solução(A,b) == sla.solve(A, b, lower=False))

[ 1. -1.  1.]
[ 1. -1.  1.]
[ True  True  True]


b)

In [ ]:
C = np.array([[7.0,-7.0,1.0],[-3.0,3.0,2.0],[7.0,7.0,-72.0]])
d = np.array([1.0,2.0,7.0])
print(solução(C,d))
print(sla.solve(C, d, lower=False))
print(solução(C,d) == sla.solve(C, d, lower=False))

[5.64285714 5.64285714 1.        ]
[5.64285714 5.64285714 1.        ]
[ True  True  True]


c)

In [ ]:
E = np.array([[1.0,2.0,3.0,4.0],[2.0,2.0,3.0,4.0],[3.0,3.0,3.0,4.0],[4.0,4.0,4.0,4.0]])
f = np.array([20.0,22.0,22.0,24.0])
print(solução(E,f))
print(sla.solve(E, f, lower=False))
print(solução(E,f) == sla.solve(E, f, lower=False))

[ 2. -2.  2.  4.]
[ 2. -2.  2.  4.]
[ True  True  True  True]
